services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: runhop
      POSTGRES_PASSWORD: runhop
      POSTGRES_DB: runhop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
  
  cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/redis_data

volumes:
  postgres_data:
  redis_data: